services:
  - xvfb

language: r

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

apt_packages:
  - tcl8.5-dev
  - tk8.5-dev
  - ghostscript

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
